# Generated by Django 4.2.3 on 2023-07-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='img',
            field=models.ImageField(default='dfghd', upload_to='pics'),
            preserve_default=False,
        ),
    ]
